### ISSUE TITLE
安装问题fatal: HTTP request failed

### ISSUE THREAD

**Issue by jeffreyhu3** [zhangzhishan/efb-filter-middleware#1]
你好，我安装使用efb wechat telegram功能正常，现在想使用filter功能。但是安装出现问题。
输入命令：pip3.6 install git+https://github.com/zhangzhishan/efb-filte
r-middleware

出现如下问题提示：
Collecting git+https://github.com/zhangzhishan/efb-filter-middleware
  Cloning https://github.com/zhangzhishan/efb-filter-middleware to /tmp/pip-hv15ljri-build
error:  while accessing https://github.com/zhangzhishan/efb-filter-middleware/info/refs

fatal: HTTP request failed
Command "git clone -q https://github.com/zhangzhishan/efb-filter-middleware /tmp/pip-hv15ljri-build" failed with error code 128 in None
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

请帮忙解决一下。谢谢！

**Comment by zhangzhishan** [comment]
看错误提示是git clone出现的问题，应该是你的git或者网络出现了问题。
