### ISSUE TITLE
Incompatible with new EHF 2.0,please update.

### ISSUE THREAD

**Issue by venorz** [zhangzhishan/efb-filter-middleware#4]
Since the new version ehforwardbot changed a lot,the middleware is now not compatible,can you update it?

**Comment by zhangzhishan** [comment]
Will try to update it.

> 
> 
> Since the new version ehforwardbot changed a lot,the middleware is now not compatible,can you update it?

**Comment by zhangzhishan** [comment]
updated~ Sorry for the long delay~~~ @venorz
